---
title: "Sipahimalani"
author: "Ambre Sipahimalani"
format: html
---
```{r}
#| message: false
#| warning: false
here::i_am("lab-grades.Rproj")
library(here)
library(ggplot2)
library(dplyr)
library(tidyr)
library(vroom)
library(readr)
library(lubridate)
```
Link to the Github repository : https://github.com/ambre-dauphine/lab-grades.git

## Question 1

```{r}
#| message: false
course <- vroom(here("data","courses.csv"))
```

## Question 2

```{r}
course|>
  arrange(course)|>
  rename(`course name`=course, identifier=course_id, `number of exams`=nb_grades)|>
    knitr::kable()
```

### Question 3 

```{r}
#| message: false
students <- read_delim(here("data","students.csv"),
                       col_types=cols(
                         id=col_integer(),
                         group=col_factor(),
                         birth_date=col_date(),
                         sex=col_factor()
                       ))
```

The `birth_date` column of the `students` data frame is of class `r class(students$birth_date)`.
The `sex` column of the `students` data frame is of class `r class(students$sex)`.

## Question 4 

```{r}
#| message: false
grades <- read_delim(here("data","grades.csv"),
                     delim="|",
                     na="$")
```


## Question 5 

```{r}
students|>
  ggplot(aes(x=group))+
  geom_bar()
```

## Question 6 

```{r}
students|>
  ggplot(aes(x=group, fill =sex))+
  geom_bar(position="fill")
```

## Question 7 

```{r}
students|>
  mutate(age=time_length(today() - birth_date, unit="year"))|>
  ggplot(aes(x=age))+
  geom_density(bw="sj")+
  geom_rug(alpha=0.1)
```

## Question 8 

```{r}
students|>
  mutate(age=time_length(today() - birth_date, unit="year"))|>
  summarise(`median age`=as.integer(round(median(age))),.by=group)|>
  knitr::kable()
```

## Question 9 

```{r}
students_a <- students|>
  mutate(age=time_length(today() - birth_date, unit="year"))

students_a |>
  summarise(age=max(age), .by=group)|>
  inner_join(students_a, by=join_by(age), keep=FALSE, suffix=c("",""))|>
  select(group, age, id, sex)|>
  arrange(desc(age))|>
  knitr::kable()
```


